---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: "nfs-test"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mariadb
  namespace: "nfs-test"
  labels:
    app: mariadb
    service: mariadb
spec:
  replicas: 1
  selector:
    app: mariadb
    service: mariadb
  strategy:
    type: Rolling
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  test: false
  triggers:
    - type: ConfigChange
  template:
    metadata:
      labels:
        app: mariadb
        service: mariadb
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - image: registry.access.redhat.com/rhscl/mariadb-102-rhel7
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'passwd'
            - name: MYSQL_USER
              value: 'passwd'
            - name: MYSQL_PASSWORD
              value: 'passwd'
            - name: MYSQL_DATABASE
              value: 'passwd'
          terminationMessagePath: /dev/termination-log
          workingDir: /
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql/data
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb

