---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: nfs-test
  namespace: velero
spec:
  backupName: nfs-test
  excludedResources:
  - node
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  includedNamespaces:
  - '*'
